namespace Meziantou.Analyzer.Rules;

internal static class UseInKeywordForInParameterCommon
{
    /// <summary>
    /// Indicates whether the argument value can be passed with an explicit <c>in</c> modifier.
    /// Without the modifier, the compiler can pass a temporary copy of a value, so the value must be a variable.
    /// </summary>
    public static bool CanBePassedByReference(IOperation operation)
    {
        while (operation is IConversionOperation conversion)
        {
            // An explicit cast is not a variable, even when the conversion is an identity conversion
            if (!conversion.IsImplicit || !conversion.Conversion.IsIdentity)
                return false;

            operation = conversion.Operand;
        }

        return operation switch
        {
            ILocalReferenceOperation localReference => !localReference.Local.IsConst,
            IParameterReferenceOperation parameterReference => !IsQueryRangeVariable(parameterReference.Parameter),
            IFieldReferenceOperation fieldReference => IsFieldVariable(fieldReference),
            IArrayElementReferenceOperation => true,
            IInstanceReferenceOperation instanceReference => instanceReference.ReferenceKind is InstanceReferenceKind.ContainingTypeInstance && instanceReference.Type is { IsValueType: true },
            _ => false,
        };
    }

    private static bool IsFieldVariable(IFieldReferenceOperation fieldReference)
    {
        if (fieldReference.Field.IsConst)
            return false;

        if (fieldReference.Instance is null)
            return true;

        // The field of a reference type instance is always a variable, but the field of a struct is a variable only when the struct is a variable
        if (fieldReference.Instance.Type is { IsReferenceType: true })
            return true;

        return CanBePassedByReference(fieldReference.Instance);
    }

    // The range variables of a query expression are the parameters of the lambdas generated by the compiler
    private static bool IsQueryRangeVariable(IParameterSymbol parameter)
        => parameter.ContainingSymbol is IMethodSymbol { MethodKind: MethodKind.AnonymousFunction, IsImplicitlyDeclared: true };
}
