<Project Sdk="Meziantou.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Meziantou.Framework.FullPath" Version="3.0.4" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
  </ItemGroup>

  <ItemGroup>
    <!-- This project is not specific to a Roslyn version, so RoslynVersion is the default version -->
    <ProjectReference Include="..\Meziantou.Analyzer.CodeFixers\Meziantou.Analyzer.CodeFixers.$(RoslynVersion).csproj" />
    <ProjectReference Include="..\Meziantou.Analyzer\Meziantou.Analyzer.$(RoslynVersion).csproj" />
  </ItemGroup>

</Project>
