using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Testing;
using Meziantou.Analyzer.Test.Harness;
using AbstractTypesTest = Meziantou.Analyzer.Test.Harness.CSharpAnalyzerTest<
    Meziantou.Analyzer.Rules.AbstractTypesShouldNotHaveConstructorsAnalyzer>;
using ClassMustBeSealedTest = Meziantou.Analyzer.Test.Harness.CSharpAnalyzerTest<
    Meziantou.Analyzer.Rules.ClassMustBeSealedAnalyzer>;
using FixToDoTest = Meziantou.Analyzer.Test.Harness.CSharpAnalyzerTest<
    Meziantou.Analyzer.Rules.FixToDoAnalyzer>;
using ObsoleteAttributeTest = Meziantou.Analyzer.Test.Harness.CSharpAnalyzerTest<
    Meziantou.Analyzer.Rules.ObsoleteAttributesShouldIncludeExplanationsAnalyzer>;

namespace Meziantou.Analyzer.Test.Rules;

/// <summary>
/// The analyzers skip generated code, except the rules that need it to be correct and the rules that report in it
/// by default such as MA0070. The <c>MEZIANTOU_ANALYZER_GENERATED_CODE</c> environment variable opts in to
/// analyzing it, and <c>report_generated_code</c> then decides what the rules report, which the tests simulate by
/// setting <c>GeneratedCodeAnalysisFlags</c>, as the rules read the variable once per process.
/// </summary>
public sealed class GeneratedCodeAnalysisTests
{
    private const GeneratedCodeAnalysisFlags OptedIn = GeneratedCodeAnalysisFlags.Analyze | GeneratedCodeAnalysisFlags.ReportDiagnostics;

    private const string GeneratedCodeWithDiagnostic = """
        // <auto-generated/>
        abstract class Test
        {
            public Test() { }
        }
        """;

    private const string GeneratedCodeWithDiagnosticReported = """
        // <auto-generated/>
        abstract class Test
        {
            public {|MA0017:Test|}() { }
        }
        """;

    [Fact]
    public Task AutoGeneratedHeader_NoDiagnosticByDefault()
    {
        var test = new AbstractTypesTest();
        test.TestCode = GeneratedCodeWithDiagnostic;

        return test.RunAsync();
    }

    [Fact]
    public Task AutoGeneratedHeader_NoDiagnosticWhenTheRuleIsConfiguredButNotOptedIn()
    {
        // MA0017 does not analyze generated code, so configuring it to report in generated code is not enough
        var test = new AbstractTypesTest();
        test.TestState.SetConfiguration("MA0017.report_generated_code", "true");
        test.TestCode = GeneratedCodeWithDiagnostic;

        return test.RunAsync();
    }

    [Fact]
    public Task AutoGeneratedHeader_NoDiagnosticWhenOptedInWithoutConfiguration()
    {
        // Opting in makes the rule analyze generated code, but its default is still to not report in it
        var test = new AbstractTypesTest();
        test.GeneratedCodeAnalysisFlags = OptedIn;
        test.TestCode = GeneratedCodeWithDiagnostic;

        return test.RunAsync();
    }

    [Fact]
    public Task AutoGeneratedHeader_DiagnosticWhenTheRuleIsConfigured()
    {
        var test = new AbstractTypesTest();
        test.GeneratedCodeAnalysisFlags = OptedIn;
        test.TestState.SetConfiguration("MA0017.report_generated_code", "true");
        test.TestCode = GeneratedCodeWithDiagnosticReported;

        return test.RunAsync();
    }

    [Fact]
    public Task AutoGeneratedHeader_DiagnosticWhenAllTheRulesAreConfigured()
    {
        var test = new AbstractTypesTest();
        test.GeneratedCodeAnalysisFlags = OptedIn;
        test.TestState.SetConfiguration("MA.report_generated_code", "true");
        test.TestCode = GeneratedCodeWithDiagnosticReported;

        return test.RunAsync();
    }

    [Fact]
    public Task AutoGeneratedHeader_RuleConfigurationWinsOverTheGlobalOne()
    {
        var test = new AbstractTypesTest();
        test.GeneratedCodeAnalysisFlags = OptedIn;
        test.TestState.SetConfiguration(("MA.report_generated_code", "true"), ("MA0017.report_generated_code", "false"));
        test.TestCode = GeneratedCodeWithDiagnostic;

        return test.RunAsync();
    }

    [Fact]
    public Task AutoGeneratedHeader_GlobalConfigurationDoesNotApplyToAnotherRule()
    {
        var test = new AbstractTypesTest();
        test.GeneratedCodeAnalysisFlags = OptedIn;
        test.TestState.SetConfiguration(("MA.report_generated_code", "false"), ("MA0053.report_generated_code", "true"));
        test.TestCode = GeneratedCodeWithDiagnostic;

        return test.RunAsync();
    }

    [Fact]
    public Task GeneratedFileName_NoDiagnosticByDefault()
    {
        var test = new AbstractTypesTest();
        test.TestState.Sources.Add(("/0/Test.g.cs", """
            abstract class Test
            {
                public Test() { }
            }
            """));

        return test.RunAsync();
    }

    [Fact]
    public Task GeneratedFileName_DiagnosticWhenTheRuleIsConfigured()
    {
        var test = new AbstractTypesTest();
        test.GeneratedCodeAnalysisFlags = OptedIn;
        test.TestState.SetConfiguration("MA0017.report_generated_code", "true");
        test.TestState.Sources.Add(("/0/Test.g.cs", """
            abstract class Test
            {
                public {|MA0017:Test|}() { }
            }
            """));

        return test.RunAsync();
    }

    [Fact]
    public Task GeneratedCodeAttribute_TheFileIsWhatMattersWhenOptedIn()
    {
        // Only the file of the diagnostic is considered, so the attribute does not hide the code of a hand written file
        var test = new AbstractTypesTest();
        test.GeneratedCodeAnalysisFlags = OptedIn;
        test.TestState.SetConfiguration("MA0017.report_generated_code", "true");
        test.TestCode = """
            [System.CodeDom.Compiler.GeneratedCode("tool", "1.0")]
            abstract class Test
            {
                public {|MA0017:Test|}() { }
            }
            """;

        return test.RunAsync();
    }

    [Fact]
    public Task GeneratedCodeAttribute_NoDiagnosticWhenNotOptedIn()
    {
        // A rule that does not analyze generated code follows the detection of Roslyn, which also considers the
        // symbols marked with [GeneratedCode] generated
        var test = new AbstractTypesTest();
        test.TestCode = """
            [System.CodeDom.Compiler.GeneratedCode("tool", "1.0")]
            abstract class Test
            {
                public Test() { }
            }
            """;

        return test.RunAsync();
    }

    [Fact]
    public Task GeneratedCodeOption_TheFileIsNotGeneratedCode()
    {
        var test = new AbstractTypesTest();
        test.TestState.SetConfiguration("generated_code", "false");
        test.TestState.Sources.Add(("/0/Test.g.cs", """
            abstract class Test
            {
                public {|MA0017:Test|}() { }
            }
            """));

        return test.RunAsync();
    }

    [Fact]
    public Task GeneratedCodeOption_TheFileIsGeneratedCode()
    {
        var test = new AbstractTypesTest();
        test.TestState.SetConfiguration("generated_code", "true");
        test.TestCode = """
            abstract class Test
            {
                public Test() { }
            }
            """;

        return test.RunAsync();
    }

    [Fact]
    public Task RuleReportingInGeneratedCodeByDefault()
    {
        var test = new ObsoleteAttributeTest();
        test.TestCode = """
            // <auto-generated/>
            class Test
            {
                [{|MA0070:System.Obsolete|}]
                public void A() { }
            }
            """;

        return test.RunAsync();
    }

    [Fact]
    public Task RuleReportingInGeneratedCodeByDefault_NoDiagnosticWhenTheRuleIsConfigured()
    {
        var test = new ObsoleteAttributeTest();
        test.TestState.SetConfiguration("MA0070.report_generated_code", "false");
        test.TestCode = """
            // <auto-generated/>
            class Test
            {
                [System.Obsolete]
                public void A() { }
            }
            """;

        return test.RunAsync();
    }

    [Fact]
    public Task SyntaxTreeRule_NoDiagnosticByDefault()
    {
        var test = new FixToDoTest();
        test.TestCode = """
            // <auto-generated/>
            // TODO
            """;

        return test.RunAsync();
    }

    [Fact]
    public Task SyntaxTreeRule_DiagnosticWhenTheRuleIsConfigured()
    {
        var test = new FixToDoTest();
        test.GeneratedCodeAnalysisFlags = OptedIn;
        test.TestState.SetConfiguration("MA0026.report_generated_code", "true");
        test.TestCode = """
            // <auto-generated/>
            // {|#0:TODO|}
            """;
        test.ExpectedDiagnostics.Add(new DiagnosticResult(RuleIdentifiers.FixToDo, DiagnosticSeverity.Warning).WithLocation(0).WithMessage("TODO "));

        return test.RunAsync();
    }

    [Fact]
    public Task GeneratedCodeIsAnalyzedWhenNotOptedIn()
    {
        // MA0053 needs generated code to be correct, so it analyzes it even when nobody opts in
        var test = new ClassMustBeSealedTest();
        test.TestState.Sources.Add(("/0/Test.cs", """
            class Test
            {
            }
            """));
        test.TestState.Sources.Add(("/0/Test.g.cs", """
            class Test2 : Test
            {
            }
            """));

        return test.RunAsync();
    }

    [Fact]
    public Task GeneratedCodeIsAnalyzedWhenOptedIn()
    {
        // The class declared in the generated file inherits from the other one, which cannot be sealed
        var test = new ClassMustBeSealedTest();
        test.GeneratedCodeAnalysisFlags = OptedIn;
        test.TestState.Sources.Add(("/0/Test.cs", """
            class Test
            {
            }
            """));
        test.TestState.Sources.Add(("/0/Test.g.cs", """
            class Test2 : Test
            {
            }
            """));

        return test.RunAsync();
    }
}
