using Microsoft.CodeAnalysis.Diagnostics;

namespace Meziantou.Analyzer.Test.Rules;

/// <summary>
/// The analyzers do not report diagnostics in generated code by default, unless the
/// <c>MEZIANTOU_ANALYZER_GENERATED_CODE</c> environment variable opts in.
/// </summary>
public sealed class GeneratedCodeAnalysisTests
{
    private const string GeneratedCodeWithDiagnostic = """
        // <auto-generated/>
        abstract class Test
        {
            public Test() { }
        }
        """;

    private const string GeneratedCodeWithDiagnosticReported = """
        // <auto-generated/>
        abstract class Test
        {
            public [|Test|]() { }
        }
        """;

    [Fact]
    public async Task AutoGeneratedHeader_NoDiagnosticByDefault()
    {
        await new ProjectBuilder()
              .WithAnalyzer<AbstractTypesShouldNotHaveConstructorsAnalyzer>()
              .WithSourceCode(GeneratedCodeWithDiagnostic)
              .ValidateAsync();
    }

    [Fact]
    public async Task AutoGeneratedHeader_DiagnosticWhenOptedIn()
    {
        await new ProjectBuilder()
              .WithAnalyzer<AbstractTypesShouldNotHaveConstructorsAnalyzer>()
              .WithGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.Analyze | GeneratedCodeAnalysisFlags.ReportDiagnostics)
              .WithSourceCode(GeneratedCodeWithDiagnosticReported)
              .ValidateAsync();
    }

    [Fact]
    public async Task GeneratedFileName_NoDiagnosticByDefault()
    {
        await new ProjectBuilder()
              .WithAnalyzer<AbstractTypesShouldNotHaveConstructorsAnalyzer>()
              .WithSourceCode("Test.g.cs", """
                abstract class Test
                {
                    public Test() { }
                }
                """)
              .ValidateAsync();
    }

    [Fact]
    public async Task GeneratedFileName_DiagnosticWhenOptedIn()
    {
        await new ProjectBuilder()
              .WithAnalyzer<AbstractTypesShouldNotHaveConstructorsAnalyzer>()
              .WithGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.Analyze | GeneratedCodeAnalysisFlags.ReportDiagnostics)
              .WithSourceCode("Test.g.cs", """
                abstract class Test
                {
                    public [|Test|]() { }
                }
                """)
              .ValidateAsync();
    }

    [Fact]
    public async Task AnalyzeOnlyRule_NoDiagnosticByDefault()
    {
        await new ProjectBuilder()
              .WithAnalyzer<ClassMustBeSealedAnalyzer>()
              .WithSourceCode("""
                // <auto-generated/>
                class Test
                {
                }

                class Test2 : Test
                {
                }
                """)
              .ValidateAsync();
    }

    [Fact]
    public async Task AnalyzeOnlyRule_DiagnosticWhenOptedIn()
    {
        await new ProjectBuilder()
              .WithAnalyzer<ClassMustBeSealedAnalyzer>()
              .WithGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.Analyze | GeneratedCodeAnalysisFlags.ReportDiagnostics)
              .WithSourceCode("""
                // <auto-generated/>
                class Test
                {
                }

                class [|Test2|] : Test
                {
                }
                """)
              .ValidateAsync();
    }
}
