using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Testing;
using Meziantou.Analyzer.Test.Harness;
using AbstractTypesTest = Meziantou.Analyzer.Test.Harness.CSharpAnalyzerTest<
    Meziantou.Analyzer.Rules.AbstractTypesShouldNotHaveConstructorsAnalyzer>;
using ClassMustBeSealedTest = Meziantou.Analyzer.Test.Harness.CSharpAnalyzerTest<
    Meziantou.Analyzer.Rules.ClassMustBeSealedAnalyzer>;
using FixToDoTest = Meziantou.Analyzer.Test.Harness.CSharpAnalyzerTest<
    Meziantou.Analyzer.Rules.FixToDoAnalyzer>;
using ObsoleteAttributeTest = Meziantou.Analyzer.Test.Harness.CSharpAnalyzerTest<
    Meziantou.Analyzer.Rules.ObsoleteAttributesShouldIncludeExplanationsAnalyzer>;

namespace Meziantou.Analyzer.Test.Rules;

/// <summary>
/// The analyzers analyze generated code, but only the rules configured with <c>report_generated_code</c>, or
/// whose default is to report in generated code such as MA0070, report the diagnostics located in it.
/// </summary>
public sealed class GeneratedCodeAnalysisTests
{
    private const string GeneratedCodeWithDiagnostic = """
        // <auto-generated/>
        abstract class Test
        {
            public Test() { }
        }
        """;

    private const string GeneratedCodeWithDiagnosticReported = """
        // <auto-generated/>
        abstract class Test
        {
            public {|MA0017:Test|}() { }
        }
        """;

    [Fact]
    public Task AutoGeneratedHeader_NoDiagnosticByDefault()
    {
        var test = new AbstractTypesTest();
        test.TestCode = GeneratedCodeWithDiagnostic;

        return test.RunAsync();
    }

    [Fact]
    public Task AutoGeneratedHeader_DiagnosticWhenTheRuleIsConfigured()
    {
        var test = new AbstractTypesTest();
        test.TestState.SetConfiguration("MA0017.report_generated_code", "true");
        test.TestCode = GeneratedCodeWithDiagnosticReported;

        return test.RunAsync();
    }

    [Fact]
    public Task AutoGeneratedHeader_DiagnosticWhenAllTheRulesAreConfigured()
    {
        var test = new AbstractTypesTest();
        test.TestState.SetConfiguration("MA.report_generated_code", "true");
        test.TestCode = GeneratedCodeWithDiagnosticReported;

        return test.RunAsync();
    }

    [Fact]
    public Task AutoGeneratedHeader_RuleConfigurationWinsOverTheGlobalOne()
    {
        var test = new AbstractTypesTest();
        test.TestState.SetConfiguration(("MA.report_generated_code", "true"), ("MA0017.report_generated_code", "false"));
        test.TestCode = GeneratedCodeWithDiagnostic;

        return test.RunAsync();
    }

    [Fact]
    public Task AutoGeneratedHeader_GlobalConfigurationDoesNotApplyToAnotherRule()
    {
        var test = new AbstractTypesTest();
        test.TestState.SetConfiguration(("MA.report_generated_code", "false"), ("MA0053.report_generated_code", "true"));
        test.TestCode = GeneratedCodeWithDiagnostic;

        return test.RunAsync();
    }

    [Fact]
    public Task GeneratedFileName_NoDiagnosticByDefault()
    {
        var test = new AbstractTypesTest();
        test.TestState.Sources.Add(("/0/Test.g.cs", """
            abstract class Test
            {
                public Test() { }
            }
            """));

        return test.RunAsync();
    }

    [Fact]
    public Task GeneratedFileName_DiagnosticWhenTheRuleIsConfigured()
    {
        var test = new AbstractTypesTest();
        test.TestState.SetConfiguration("MA0017.report_generated_code", "true");
        test.TestState.Sources.Add(("/0/Test.g.cs", """
            abstract class Test
            {
                public {|MA0017:Test|}() { }
            }
            """));

        return test.RunAsync();
    }

    [Fact]
    public Task GeneratedCodeAttribute_TheFileIsWhatMatters()
    {
        // Only the file of the diagnostic is considered, so the attribute does not hide the code of a hand written file
        var test = new AbstractTypesTest();
        test.TestCode = """
            [System.CodeDom.Compiler.GeneratedCode("tool", "1.0")]
            abstract class Test
            {
                public {|MA0017:Test|}() { }
            }
            """;

        return test.RunAsync();
    }

    [Fact]
    public Task GeneratedCodeOption_TheFileIsNotGeneratedCode()
    {
        var test = new AbstractTypesTest();
        test.TestState.SetConfiguration("generated_code", "false");
        test.TestState.Sources.Add(("/0/Test.g.cs", """
            abstract class Test
            {
                public {|MA0017:Test|}() { }
            }
            """));

        return test.RunAsync();
    }

    [Fact]
    public Task GeneratedCodeOption_TheFileIsGeneratedCode()
    {
        var test = new AbstractTypesTest();
        test.TestState.SetConfiguration("generated_code", "true");
        test.TestCode = """
            abstract class Test
            {
                public Test() { }
            }
            """;

        return test.RunAsync();
    }

    [Fact]
    public Task RuleReportingInGeneratedCodeByDefault()
    {
        var test = new ObsoleteAttributeTest();
        test.TestCode = """
            // <auto-generated/>
            class Test
            {
                [{|MA0070:System.Obsolete|}]
                public void A() { }
            }
            """;

        return test.RunAsync();
    }

    [Fact]
    public Task RuleReportingInGeneratedCodeByDefault_NoDiagnosticWhenTheRuleIsConfigured()
    {
        var test = new ObsoleteAttributeTest();
        test.TestState.SetConfiguration("MA0070.report_generated_code", "false");
        test.TestCode = """
            // <auto-generated/>
            class Test
            {
                [System.Obsolete]
                public void A() { }
            }
            """;

        return test.RunAsync();
    }

    [Fact]
    public Task SyntaxTreeRule_NoDiagnosticByDefault()
    {
        var test = new FixToDoTest();
        test.TestCode = """
            // <auto-generated/>
            // TODO
            """;

        return test.RunAsync();
    }

    [Fact]
    public Task SyntaxTreeRule_DiagnosticWhenTheRuleIsConfigured()
    {
        var test = new FixToDoTest();
        test.TestState.SetConfiguration("MA0026.report_generated_code", "true");
        test.TestCode = """
            // <auto-generated/>
            // {|#0:TODO|}
            """;
        test.ExpectedDiagnostics.Add(new DiagnosticResult(RuleIdentifiers.FixToDo, DiagnosticSeverity.Warning).WithLocation(0).WithMessage("TODO "));

        return test.RunAsync();
    }

    [Fact]
    public Task GeneratedCodeIsAnalyzed()
    {
        // The class declared in the generated file inherits from the other one, which cannot be sealed
        var test = new ClassMustBeSealedTest();
        test.TestState.Sources.Add(("/0/Test.cs", """
            class Test
            {
            }
            """));
        test.TestState.Sources.Add(("/0/Test.g.cs", """
            class Test2 : Test
            {
            }
            """));

        return test.RunAsync();
    }
}
